/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

// #define CONFIG_FLASH_DRIVER_EXECUTES_FROM_RAM 0
// #define CONFIG_ENABLE_QUICKACCESS_SECTION_IN_XSPI_DRIVER 0
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0
#define CONFIG_MPP_OS_FREERTOS 1
#define CONFIG_MPP_OS_NAME freertos
#define CONFIG_MPP_RC_TASK_STACK_SIZE 1200
#define CONFIG_MPP_PR_TASK_STACK_SIZE 1200

#endif /* _MCUX_CONFIG_H_ */
