<#
.SYNOPSIS
    Scans a CodeWarrior for MCUs (v11.1+, Eclipse-based) install tree for
    the confirmed real executables — ecd.exe, cwide.exe/cwidec.exe,
    fflash.exe — and writes their paths to config/toolchain.ps1.

.DESCRIPTION
    Unlike the legacy v8.x "Classic" CodeWarrior tools, CW10/11's build and
    debug entry points are well-documented and version-stable:
      - eclipse\ecd.exe          headless build driver
      - eclipse\cwide.exe/cwidec.exe   runs Debugger Shell TCL scripts
      - the 56800E flash programmer, fflash.exe
    See docs/ARCHITECTURE.md for sources. This script still searches by
    pattern rather than a single hardcoded path, since the exact install
    folder name (e.g. "CW MCU v11.1") is user-chosen.

.PARAMETER CwRoot
    Root of your CodeWarrior for MCUs installation, e.g.
    "C:\Freescale\CW MCU v11.1".

.EXAMPLE
    .\tools\Detect-Toolchain.ps1 -CwRoot "C:\Freescale\CW MCU v11.1"
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$CwRoot
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $CwRoot)) {
    Write-Error "CwRoot not found: $CwRoot"
    exit 1
}

Write-Host "Scanning $CwRoot for CodeWarrior CLI tools..." -ForegroundColor Cyan

$patterns = [ordered]@{
    Build            = @('ecd.exe')
    DebuggerShell    = @('cwidec.exe', 'cwide.exe')
    FlashProgrammer  = @('fflash.exe')
    Make             = @('make.exe')
}

$found = [ordered]@{}
$ambiguous = @()

foreach ($role in $patterns.Keys) {
    $matches = @()
    foreach ($pat in $patterns[$role]) {
        $matches += Get-ChildItem -Path $CwRoot -Recurse -File -Filter $pat -ErrorAction SilentlyContinue
    }
    $matches = $matches | Select-Object -ExpandProperty FullName -Unique

    if ($matches.Count -eq 0) {
        Write-Host "  [MISSING] $role — no match for $($patterns[$role] -join ', '). See docs/SETUP.md step 4." -ForegroundColor Yellow
        $found[$role] = $null
    }
    elseif ($matches.Count -eq 1) {
        Write-Host "  [OK]      $role -> $($matches[0])" -ForegroundColor Green
        $found[$role] = $matches[0]
    }
    else {
        Write-Host "  [MULTIPLE] $role — found $($matches.Count) candidates, picking first; edit config/toolchain.ps1 if wrong:" -ForegroundColor Yellow
        $matches | ForEach-Object { Write-Host "             $_" }
        $found[$role] = $matches[0]
        $ambiguous += $role
    }
}

$configDir = Join-Path $PSScriptRoot '..\config'
$configPath = Join-Path $configDir 'toolchain.ps1'

$lines = @(
    "# Auto-generated by tools/Detect-Toolchain.ps1 on $(Get-Date -Format o)"
    "# CwRoot: $CwRoot"
    "# Machine-specific — not committed to git (see .gitignore)."
    ""
    "`$CwRoot = '$CwRoot'"
    "`$ECD    = '$($found.Build)'"
    "`$CWIDE  = '$($found.DebuggerShell)'"
    "`$FLASH  = '$($found.FlashProgrammer)'"
    "`$MAKE   = '$($found.Make)'"
)
Set-Content -Path $configPath -Value $lines -Encoding UTF8

Write-Host ""
Write-Host "Wrote $configPath" -ForegroundColor Cyan

if ($found.Values -contains $null) {
    Write-Host "Some tools were not found automatically — fill them in by hand in config/toolchain.ps1 (see docs/SETUP.md step 4)." -ForegroundColor Yellow
}
if ($ambiguous.Count -gt 0) {
    Write-Host "Ambiguous matches for: $($ambiguous -join ', ') — verify config/toolchain.ps1 picked the right one (e.g. multiple CodeWarrior versions installed)." -ForegroundColor Yellow
}
