<#
.SYNOPSIS
    Scans a CodeWarrior for 56800/56800E install tree for the real
    compiler/assembler/linker/flash-programmer/debugger executables and
    writes their paths to config/toolchain.ps1.

.DESCRIPTION
    CodeWarrior's command-line tool executable names have changed across
    versions (v7.x/v8.x vs v10.x/v11.x). Rather than hardcode a guess that
    might be wrong for your install, this script searches by pattern and
    reports what it actually finds, so config/toolchain.ps1 always
    reflects real paths on this machine.

.PARAMETER CwRoot
    Root of your CodeWarrior for 56800/56800E installation, e.g.
    "C:\Program Files (x86)\Freescale\CW MCU v11.2".

.EXAMPLE
    .\tools\Detect-Toolchain.ps1 -CwRoot "C:\Program Files (x86)\Freescale\CW MCU v11.2"
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$CwRoot
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $CwRoot)) {
    Write-Error "CwRoot not found: $CwRoot"
    exit 1
}

Write-Host "Scanning $CwRoot for 56800/56800E command-line tools..." -ForegroundColor Cyan

# Pattern -> role. Patterns are deliberately loose (mwcc*/mwld*/mwasm* covers
# both the mwcc56800/mwcc56800e and similarly-named linker/assembler variants
# seen across CW releases); flash/debugger tools are matched by keyword since
# their executable names are less standardized.
$patterns = [ordered]@{
    Compiler       = @('mwcc*56800*.exe', 'ccdsc*.exe')
    Assembler      = @('mwasm*56800*.exe', 'mwasmdsp*.exe')
    Linker         = @('mwld*56800*.exe')
    FlashProgrammer = @('*56800*Flash*Programmer*.exe', '*FlashProgrammer*56800*.exe', '*DSC*Flash*.exe')
    DebuggerShell  = @('cwdebug*.exe', '*Debugger*Shell*.exe', 'cwidecmdline.exe')
}

$found = [ordered]@{}
$ambiguous = @()

foreach ($role in $patterns.Keys) {
    $matches = @()
    foreach ($pat in $patterns[$role]) {
        $matches += Get-ChildItem -Path $CwRoot -Recurse -File -Filter $pat -ErrorAction SilentlyContinue
    }
    $matches = $matches | Select-Object -ExpandProperty FullName -Unique

    if ($matches.Count -eq 0) {
        Write-Host "  [MISSING] $role — no match. See docs/SETUP.md step 4." -ForegroundColor Yellow
        $found[$role] = $null
    }
    elseif ($matches.Count -eq 1) {
        Write-Host "  [OK]      $role -> $($matches[0])" -ForegroundColor Green
        $found[$role] = $matches[0]
    }
    else {
        Write-Host "  [MULTIPLE] $role — found $($matches.Count) candidates, picking first; edit config/toolchain.ps1 if wrong:" -ForegroundColor Yellow
        $matches | ForEach-Object { Write-Host "             $_" }
        $found[$role] = $matches[0]
        $ambiguous += $role
    }
}

$configDir = Join-Path $PSScriptRoot '..\config'
$configPath = Join-Path $configDir 'toolchain.ps1'

$lines = @(
    "# Auto-generated by tools/Detect-Toolchain.ps1 on $(Get-Date -Format o)"
    "# CwRoot: $CwRoot"
    "# Machine-specific — not committed to git (see .gitignore)."
    ""
    "`$CwRoot = '$CwRoot'"
    "`$CC     = '$($found.Compiler)'"
    "`$ASM    = '$($found.Assembler)'"
    "`$LD     = '$($found.Linker)'"
    "`$FLASH  = '$($found.FlashProgrammer)'"
    "`$DEBUG  = '$($found.DebuggerShell)'"
)
Set-Content -Path $configPath -Value $lines -Encoding UTF8

Write-Host ""
Write-Host "Wrote $configPath" -ForegroundColor Cyan

if ($found.Values -contains $null) {
    Write-Host "Some tools were not found automatically — fill them in by hand in config/toolchain.ps1 (see docs/SETUP.md step 4)." -ForegroundColor Yellow
}
if ($ambiguous.Count -gt 0) {
    Write-Host "Ambiguous matches for: $($ambiguous -join ', ') — verify config/toolchain.ps1 picked the right one." -ForegroundColor Yellow
}
