/*
 * Copyright 2020-2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: MC56F83789
package_id: MC56F83789VLL
mcu_data: ksdk2_0
processor_version: 0.10.10
board: MC56F83000-EVK
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '3', peripheral: OCCS, signal: EXTAL, pin_signal: GPIOC0/EXTAL/CLKIN0}
  - {pin_num: '4', peripheral: OCCS, signal: XTAL, pin_signal: GPIOC1/XTAL}
  - {pin_num: '9', peripheral: QSCI2, signal: TXD, pin_signal: GPIOD6/TXD2/XB_IN4/XB_OUT8}
  - {pin_num: '10', peripheral: QSCI2, signal: RXD, pin_signal: GPIOD5/RXD2/XB_IN5/XB_OUT9}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* GPIOD IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOD);
    /* Enable peripheral functionality on pin GPIOC0 (pin 3) */
    GPIO_PinSetPeripheralMode(BOARD_EXTAL_GPIO, BOARD_EXTAL_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC0 (pin 3) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C0_EXTAL);
    /* Enable peripheral functionality on pin GPIOC1 (pin 4) */
    GPIO_PinSetPeripheralMode(BOARD_XTAL_GPIO, BOARD_XTAL_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOD5 (pin 10) */
    GPIO_PinSetPeripheralMode(BOARD_RXD_BDM_GPIO, BOARD_RXD_BDM_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOD5 (pin 10) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_D5_RXD2);
    /* Enable peripheral functionality on pin GPIOD6 (pin 9) */
    GPIO_PinSetPeripheralMode(BOARD_TXD_BDM_GPIO, BOARD_TXD_BDM_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOD6 (pin 9) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_D6_TXD2);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
